# Generated by Django 4.0.2 on 2022-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('flatno', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('China', 'China'), ('Japan', 'Japan')], max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='about/')),
            ],
        ),
    ]
